export const SHOW_ONLINE_USERS = "SHOW_ONLINE_USERS"
export const HIDE_ONLINE_USERS = "HIDE_ONLINE_USERS"
export const SHOW_OFFLINE_USERS = "SHOW_OFFLINE_USERS"
export const HIDE_OFFLINE_USERS = "HIDE_OFFLINE_USERS"